// <auto-generated />
using System;
using Combat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Combat.Infrastructure.Migrations
{
    [DbContext(typeof(CombatDbContext))]
    [Migration("20261001074810_AddMonsterGeneration")]
    partial class AddMonsterGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Combat.Domain.Entities.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MonsterId");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterBaseAttack");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterBaseDefense");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterBaseHealth");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterBaseSpeed");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MonsterClass");

                    b.Property<Guid>("DungeonRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("MonsterDungeonRunId");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("MonsterIdempotencyKey");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("MonsterImageUrl");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterLevel");

                    b.Property<Guid>("MonsterDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("MonsterDefinitionId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MonsterName");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterPlayerCount");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MonsterDefinitionId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Combat.Domain.Entities.MonsterDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MonsterDefinitionId");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterDefinitionBaseAttack");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterDefinitionBaseDefense");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterDefinitionBaseHealth");

                    b.Property<int>("BaseSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("MonsterDefinitionBaseSpeed");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MonsterDefinitionClass");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("MonsterDefinitionImageUrl");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MonsterDefinitionName");

                    b.HasKey("Id");

                    b.HasIndex("Class");

                    b.ToTable("MonsterDefinitions");
                });

            modelBuilder.Entity("Combat.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PlayerId");

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerAttack");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerHealth");

                    b.Property<int>("MaxHealth")
                        .HasColumnType("integer")
                        .HasColumnName("PlayerMaxHealth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("PlayerName");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Combat.Domain.Entities.Monster", b =>
                {
                    b.HasOne("Combat.Domain.Entities.MonsterDefinition", "MonsterDefinition")
                        .WithMany()
                        .HasForeignKey("MonsterDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonsterDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
